### ISSUE TITLE
Installation of Catmandu-Exporter-Table on Centos 6.4

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-Exporter-Table#6]
Trying to prepare a fresh centos 6.4 with Catmandu-Exporter-Table it failes to install Text-MarkdownTable-0.2.3:

    cpanm (App::cpanminus) 1.7014 on perl 5.010001 built for x86_64-linux-thread-multi 
    Work directory is /root/.cpanm/work/1413894047.29844
    You have make /usr/bin/make
    You have LWP 5.833
    You have /bin/tar: tar (GNU tar) 1.23
    Copyright (C) 2010 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Written by John Gilmore and Jay Fenlason.
    You have /usr/bin/unzip
    Searching Text::MarkdownTable on cpanmetadb ...
    --> Working on Text::MarkdownTable
    Fetching http://www.cpan.org/authors/id/V/VO/VOJ/Text-MarkdownTable-0.2.3.tar.gz
    -> OK
    Unpacking Text-MarkdownTable-0.2.3.tar.gz
    Entering Text-MarkdownTable-0.2.3
    Checking configure dependencies from META.json
    Checking if you have Module::Build::Tiny 0.036 ... Yes (0.039)
    Configuring Text-MarkdownTable-0.2.3
    Running Build.PL
    Creating new 'Build' script for 'Text-MarkdownTable' version '0.2.3'
    -> OK
    Checking dependencies from MYMETA.json ...
    Checking if you have Moo 1.0 ... Yes (1.006000)
    Checking if you have IO::Handle::Util 0.01 ... Yes (0.01)
    Building and testing Text-MarkdownTable-0.2.3
    cp lib/Text/MarkdownTable.pm blib/lib/Text/MarkdownTable.pm
    t/file.t ................ ok
    t/release-pod-syntax.t .. skipped: these tests are for release candidate testing
    coercion for "widths" failed: Use of uninitialized value $_ in length at           /root/.cpanm/work/1413894047.29844/Text-MarkdownTable-0.2.3/blib/lib/Text/MarkdownTable.pm line 54.
    # Tests were run but no plan was declared and done_testing() was not seen.
    # Looks like your test exited with 255 just after 5.
    t/simple.t ..............
    Dubious, test returned 255 (wstat 65280, 0xff00)
    All 5 subtests passed

    Test Summary Report
    -------------------
    t/simple.t            (Wstat: 65280 Tests: 5 Failed: 0)
      Non-zero exit status: 255
      Parse errors: No plan found in TAP output
    Files=3, Tests=11,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.12 cusr  0.01 csys =  0.16 CPU) 
    Result: FAIL
    -> FAIL Installing Text::MarkdownTable failed. See /root/.cpanm/work/1413894047.29844/build.log for details. Retry with --force to force install it.

**Comment by nichtich** [comment]
Can you please try again with the current version?

**Comment by phochste** [comment]
Works for me!
